blank_issues_enabled: false
contact_links:
  - name: 🙋 General Questions or Help
    url: https://github.com/Shiva-302004/Conference_website/discussions
    about: For help, questions, or usage support, please use GitHub Discussions.
